input = """
>Rosalind_0739
TATAATTGACACAAAAGCTCCACAGCTTTTTGATGCATAATATAATCGCGCACAAACCAC
AATCCTGGCCCGAGCACGCAATCTGACTGACGTGCGTGTATTAATAAGAGGTAGCCCGTG
TTCCGGACTTCCTATAGGACGGCTTACCGCATTTATTGCTAGTGCGGTCACTCTGGTCTT
CGATGCGTCGAGAAGCTAAGATTGCGGGTCCCAAAAACTCATTTGTATTCGCGGGGTTCA
ACGGGCAGCAGAGTAAATATGTGTTGCAGAAAGAACCTGGGTGCCCCCGGGTCCGCTTTA
GGGAGTTCTACTTACGATGCACTACGTTTTCAAAGAGGCTGTTTCAAGGTATGGGAGCGA
ATTATTGGCTCTTGAACACCACATGAGCGGCTCCTCATGTTATTCATTCAGTGGTCTCGG
TACCTATTGCCCTAAGTGCTGTAACCGGAGGGCCCTCCTATGGCAAGTCGTTTTCTTCTT
GGACATTGAGGCTTACTCTCTGGACAACTGAGAACGAGGGAGTAGAGTCGTAAAAGTTGG
GTTGTTAACATTCGCGCCCTATATGCAATGGGTCAACTCCACAGCATCATGGCAATCCCT
CCACTGCCGCGTCAATACATTTACTCAGATACCCCCAATACGGAGCAGATGTCGGAAACA
AGTAGTGGTTAAACGGATAAGAAAGCAATTAGCGCCCTCGAACCTTCACCTACAAAACTG
CGAAAGAAGTTAAACCGTACCGCCGTTAAGGGCAGAAGTGGGGTCGGCTTTATCTTCCTC
TGCAACATAACGGTCGTCGGTCAACTCGAATCAAAAGGGCTACTACGGGAAACGCCAGCC
TCTATTCCGTGGATGTCCACCTGAGCGGCTCGCGGGAGTCGAGACCGTTGGAAGACATTC
CGCG
""".split()[1:]
input = ''.join(input).strip()

print len(input)

def isPalindrome(input):
	compDict = {'A':'T','T':'A','G':'C','C':'G'}
	complement = ''.join([compDict[input[i]] for i in range(len(input))])
	if complement[::-1] == input:
		return True
	return False

for i in range(len(input)):
	for j in range(4, 13):
		if len(input[i:i+j]) == j and isPalindrome(input[i:i+j]):
			print i+1, j