"""input = "TACGAATCTTAAGGCGGGATTTGGATGTATTTGGATTTTGGATTTTGGATATATTTGGATTTTGGATCTTACCATATTTGGATATTTGGATTCGTTTGGATATCGGTCATTTTGGATCCTTTGGATAACTTTGGATCTCCCTTTGGATGATTTGGATTAGTCAGCTTGAGCGGGCTGTTTGGATAGTTTGGATTTTGGATTAAATTTGGATGGTTTGGATTTTTGGATGTTTGGATCTTTGGATTGATTTGGATTTATTTTGGATATTTTGGATGTTTTGGATAATCCTCCACTTTGGATATTAGACTTTGGATTGGTTTGGATTTTGGATGTTTGGATTTTGGATTGCATTTGGATATGGCTTTGGATTTTGGATGGAACTTCCAGTAGTTTGGATAACGGTTTTGGATCAAGTTTGGATAAGAAGTTTGGATGTGGTCAGCGAGTTCGCTTTGGATTTTGGATTATTTGGATGATGTTTGGATCTTTGGATTCCCTTTGGATAGTTTGGATTTTTTGGATTTTGGATTTTGGATACTATATTTTGGATGATCTTTGGATTTTGGATTTTGGATCCTTTTGGATATTTGGATACCCTTTTGGATGTTTGGATATTTGGATCAAGCCGGGCCCGAGGGTTTGGATATTTGGATCTTTGGATTTTGGATCTTTGGATTGTCAGGTTTGGATTTTGGATTTTGGATAACGCGGCTTTTGGATCGTGCCTTCGTTTGGATCCTTTTGGATCCTTTGGATGTTTGGATTTTGGATGGACCGATTTGGATTTGTTTGGATTTTGGATCAAGTGACTTTTGGATTTTGGATAGTTTGGATTTGTTTTGGATTTTTGGATTGTTGTTTGGATTGCTCGTTTGGATGTTTGGATTCGTTTGGATGCTTTGGATGTTTGGATAAATTTGGATTTTGGATTTTGGATCGATTTGGATCTTTGGATTTTGGATCTTTGGAT" #String phrase
motif = "TTTGGATTT" #Substring to find

def Main():
	for i in getMotif():
		print i,
	
def getMotif():
	listOfIndices = []
	for i in range(len(input)):
		if motif == input[i:i+len(motif)]:
			listOfIndices.append(i+1)
	return listOfIndices

if __name__ == "__main__":
	Main()"""
#Much simpler solution...
	
s,t = open('input.txt').read().split('\r\n')

for i in range(len(s)):
	if s[i:].startswith(t):
		print i+1,